baseURL = "https://the-huddle.indiaultimate.org/"
languageCode = "en-us"
title = "The Huddle"
theme = "kube"
Paginate = 10000

[Params]
    RSSLink = "/index.xml"
    description = "An archive of The Huddle — an Ultimate magazine."
    author = "the-huddle" # add your company name
    github = "" # add your github profile name
    twitter = "" # add your twitter profile
    email = "myemail@myaddress.xxx"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Authors"
    weight = 2
    url = "/author/"

[taxonomies]
    authors = "author"